# -*- coding: utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


#
# 食材の追加
#

# カテゴリー：肉
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛モモかたまり')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛モモスライス')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛カレーシチュー用')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛焼肉用')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛すき焼き用')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛ステーキ用')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛すじ')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛ホルモン')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛挽き肉')
Food.create(:category => FD_CATEGORY_MEAT, :name => '合挽き肉')
Food.create(:category => FD_CATEGORY_MEAT, :name => '牛薄切り（切り落とし・こま切れ）')
Food.create(:category => FD_CATEGORY_MEAT, :name => 'その他の牛肉')

Food.create(:category => FD_CATEGORY_MEAT, :name => '豚バラスライス')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚バラかたまり')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚ももかたまり')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚ももスライス')
Food.create(:category => FD_CATEGORY_MEAT, :name => 'とんかつ用')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚挽き肉')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚薄切り（切り落とし・こま切れ）')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚ヒレかたまり')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚スペアリブ')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚しゃぶしゃぶ用')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚ホルモン')
Food.create(:category => FD_CATEGORY_MEAT, :name => '豚足')
Food.create(:category => FD_CATEGORY_MEAT, :name => 'その他の豚肉')

Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏挽き肉')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏もも肉')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏ムネ肉')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏ささみ')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏手羽元')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏手羽中')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏手羽先')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏砂肝')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏レバー')
Food.create(:category => FD_CATEGORY_MEAT, :name => '鶏ホルモン')
Food.create(:category => FD_CATEGORY_MEAT, :name => 'その他の鶏肉')


# カテゴリー：魚介
Food.create(:category => FD_CATEGORY_FISH, :name => 'あさり')
Food.create(:category => FD_CATEGORY_FISH, :name => 'あじ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'イカ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'イクラ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'いわし')
Food.create(:category => FD_CATEGORY_FISH, :name => 'うなぎ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'ウニ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'えび')
Food.create(:category => FD_CATEGORY_FISH, :name => 'カサゴ（アラカブ）')
Food.create(:category => FD_CATEGORY_FISH, :name => 'かつお')
Food.create(:category => FD_CATEGORY_FISH, :name => 'カニ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'カレイ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'カワハギ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'キス')
Food.create(:category => FD_CATEGORY_FISH, :name => 'さけ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'さば')
Food.create(:category => FD_CATEGORY_FISH, :name => 'さんま')
Food.create(:category => FD_CATEGORY_FISH, :name => '塩さば')
Food.create(:category => FD_CATEGORY_FISH, :name => 'しじみ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'ししゃも')
Food.create(:category => FD_CATEGORY_FISH, :name => 'シーフードミックス')
Food.create(:category => FD_CATEGORY_FISH, :name => '鯛')
Food.create(:category => FD_CATEGORY_FISH, :name => 'タコ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'タチウオ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'タラ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'ひらめ')
Food.create(:category => FD_CATEGORY_FISH, :name => 'ぶり')
Food.create(:category => FD_CATEGORY_FISH, :name => '明太子')
Food.create(:category => FD_CATEGORY_FISH, :name => 'その他の魚介')


# カテゴリ：野菜
Food.create(:category => FD_CATEGORY_VEGE, :name => 'アスパラガス')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'アボカド')
Food.create(:category => FD_CATEGORY_VEGE, :name => '枝豆')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'えのき')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'エリンギ')
Food.create(:category => FD_CATEGORY_VEGE, :name => '大葉')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'おくら')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'かいわれ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'かぶ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'かぼちゃ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'カリフラワー')
Food.create(:category => FD_CATEGORY_VEGE, :name => '絹さや')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'キャベツ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'きゅうり')
Food.create(:category => FD_CATEGORY_VEGE, :name => '栗')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'グリーンピース')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ゴーヤ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ゴボウ')
Food.create(:category => FD_CATEGORY_VEGE, :name => '小松菜')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'さつまいも')
Food.create(:category => FD_CATEGORY_VEGE, :name => '里いも')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'さやいんげん')
Food.create(:category => FD_CATEGORY_VEGE, :name => '山菜ミックス')
Food.create(:category => FD_CATEGORY_VEGE, :name => '椎茸')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'しめじ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'じゃがいも')
Food.create(:category => FD_CATEGORY_VEGE, :name => '春菊')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'しょうが')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'すだち')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ズッキーニ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'セロリ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'そら豆')
Food.create(:category => FD_CATEGORY_VEGE, :name => '大根')
Food.create(:category => FD_CATEGORY_VEGE, :name => '大根の葉')
Food.create(:category => FD_CATEGORY_VEGE, :name => '大豆')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'たけのこ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'たまねぎ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'チンゲン菜')
Food.create(:category => FD_CATEGORY_VEGE, :name => '冬瓜')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'とうもろこし')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'トマト')
Food.create(:category => FD_CATEGORY_VEGE, :name => '長いも')
Food.create(:category => FD_CATEGORY_VEGE, :name => '長ネギ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'なす')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'なめこ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ニラ')
Food.create(:category => FD_CATEGORY_VEGE, :name => '人参')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'にんにく')
Food.create(:category => FD_CATEGORY_VEGE, :name => '白菜')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'パプリカ')
Food.create(:category => FD_CATEGORY_VEGE, :name => '万能ネギ')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ピーマン')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ふき')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ブロッコリー')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ホウレンソウ')
Food.create(:category => FD_CATEGORY_VEGE, :name => '舞茸')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'マッシュルーム')
Food.create(:category => FD_CATEGORY_VEGE, :name => '水菜')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'ミックスベジタブル')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'みつば')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'もやし')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'レタス')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'レンコン')
Food.create(:category => FD_CATEGORY_VEGE, :name => 'その他の野菜')


# カテゴリ：主食・卵乳製品
Food.create(:category => FD_CATEGORY_EGG, :name => '米')
Food.create(:category => FD_CATEGORY_EGG, :name => 'もち米')
Food.create(:category => FD_CATEGORY_EGG, :name => 'ごはん')
Food.create(:category => FD_CATEGORY_EGG, :name => '食パン')
Food.create(:category => FD_CATEGORY_EGG, :name => 'ロールパン')
Food.create(:category => FD_CATEGORY_EGG, :name => 'クルトン')
Food.create(:category => FD_CATEGORY_EGG, :name => 'その他の米・パン')

Food.create(:category => FD_CATEGORY_EGG, :name => 'スパゲティ')
Food.create(:category => FD_CATEGORY_EGG, :name => 'マカロニ')
Food.create(:category => FD_CATEGORY_EGG, :name => 'うどん')
Food.create(:category => FD_CATEGORY_EGG, :name => 'そば')
Food.create(:category => FD_CATEGORY_EGG, :name => 'そうめん')
Food.create(:category => FD_CATEGORY_EGG, :name => 'ちゃんぽん')
Food.create(:category => FD_CATEGORY_EGG, :name => '焼きそば')
Food.create(:category => FD_CATEGORY_EGG, :name => 'その他の麺')

Food.create(:category => FD_CATEGORY_EGG, :name => '卵')
Food.create(:category => FD_CATEGORY_EGG, :name => 'うずら卵')
Food.create(:category => FD_CATEGORY_EGG, :name => '牛乳')
Food.create(:category => FD_CATEGORY_EGG, :name => '生クリーム')
Food.create(:category => FD_CATEGORY_EGG, :name => 'ヨーグルト')
Food.create(:category => FD_CATEGORY_EGG, :name => 'スライスチーズ')
Food.create(:category => FD_CATEGORY_EGG, :name => '粉チーズ')
Food.create(:category => FD_CATEGORY_EGG, :name => '練乳')
Food.create(:category => FD_CATEGORY_EGG, :name => '豆乳')
Food.create(:category => FD_CATEGORY_EGG, :name => 'バター')
Food.create(:category => FD_CATEGORY_EGG, :name => 'マーガリン')
Food.create(:category => FD_CATEGORY_EGG, :name => 'ブルーチーズ')
Food.create(:category => FD_CATEGORY_EGG, :name => 'クリームチーズ')
Food.create(:category => FD_CATEGORY_EGG, :name => 'ピザ用チーズ')
Food.create(:category => FD_CATEGORY_EGG, :name => 'その他の卵・乳製品')

Food.create(:category => FD_CATEGORY_EGG, :name => '薄力粉')
Food.create(:category => FD_CATEGORY_EGG, :name => '中力粉')
Food.create(:category => FD_CATEGORY_EGG, :name => '強力粉')
Food.create(:category => FD_CATEGORY_EGG, :name => '天ぷら粉')
Food.create(:category => FD_CATEGORY_EGG, :name => '片栗粉')
Food.create(:category => FD_CATEGORY_EGG, :name => 'ホットケーキミックス')
Food.create(:category => FD_CATEGORY_EGG, :name => 'お好み焼き粉')
Food.create(:category => FD_CATEGORY_EGG, :name => '白玉粉')
Food.create(:category => FD_CATEGORY_EGG, :name => 'ベーキングパウダー')
Food.create(:category => FD_CATEGORY_EGG, :name => 'きなこ')
Food.create(:category => FD_CATEGORY_EGG, :name => 'パン粉')
Food.create(:category => FD_CATEGORY_EGG, :name => 'コーンスターチ')
Food.create(:category => FD_CATEGORY_EGG, :name => 'その他の粉')


# カテゴリ：加工品・乾物・海藻・レトルト
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ハム')
Food.create(:category => FD_CATEGORY_RETORT, :name => '生ハム')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ウインナー')
Food.create(:category => FD_CATEGORY_RETORT, :name => '焼き豚')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ベーコン')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ミートボール')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'チキンナゲット')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'その他の肉加工品')

Food.create(:category => FD_CATEGORY_RETORT, :name => '豆腐（絹）')
Food.create(:category => FD_CATEGORY_RETORT, :name => '豆腐（木綿）')
Food.create(:category => FD_CATEGORY_RETORT, :name => '油揚げ')
Food.create(:category => FD_CATEGORY_RETORT, :name => '厚揚げ')
Food.create(:category => FD_CATEGORY_RETORT, :name => '納豆')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'こんにゃく')
Food.create(:category => FD_CATEGORY_RETORT, :name => '糸こんにゃく')
Food.create(:category => FD_CATEGORY_RETORT, :name => '餃子の皮')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'その他の植物加工品')

Food.create(:category => FD_CATEGORY_RETORT, :name => 'カニ風味かまぼこ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'かまぼこ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'がんもどき')
Food.create(:category => FD_CATEGORY_RETORT, :name => '魚肉ソーセージ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'さつまあげ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'チーズかまぼこ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ちくわ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'つみれ（魚）')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'つみれ（肉）')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'はんぺん')
Food.create(:category => FD_CATEGORY_RETORT, :name => '丸・角天')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'その他の練り物')

Food.create(:category => FD_CATEGORY_RETORT, :name => 'かつおぶし')
Food.create(:category => FD_CATEGORY_RETORT, :name => '寒天')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'きくらげ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'こうや豆腐')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'こんぶ')
Food.create(:category => FD_CATEGORY_RETORT, :name => '桜えび')
Food.create(:category => FD_CATEGORY_RETORT, :name => '塩昆布')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ゼラチン')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ちりめんじゃこ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ところてん')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'とろろ昆布')
Food.create(:category => FD_CATEGORY_RETORT, :name => '海苔')
Food.create(:category => FD_CATEGORY_RETORT, :name => '春雨')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ひじき')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ふ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'マロニー')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'めかぶ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'もずく')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ワカメ（乾燥）')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ワカメ（生）')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'その他の乾物・海藻')

Food.create(:category => FD_CATEGORY_RETORT, :name => '梅干')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'キムチ')
Food.create(:category => FD_CATEGORY_RETORT, :name => '高菜')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'たくあん')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'らっきょ')
Food.create(:category => FD_CATEGORY_RETORT, :name => '野沢菜')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'その他の漬物')

Food.create(:category => FD_CATEGORY_RETORT, :name => 'あさり缶')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'アンチョビ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'いわし缶')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'オイルサーディン')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'コンビーフ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ザーサイ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'さけ缶')
Food.create(:category => FD_CATEGORY_RETORT, :name => '鮭フレーク')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'さば缶')
Food.create(:category => FD_CATEGORY_RETORT, :name => '塩辛')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ジャム')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'スパム')
Food.create(:category => FD_CATEGORY_RETORT, :name => '食べるラー油')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ツナ缶')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'トマト缶')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'なめたけ')
Food.create(:category => FD_CATEGORY_RETORT, :name => '海苔佃煮')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ピーナツバター')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ふりかけ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'その他の瓶類・缶類')

Food.create(:category => FD_CATEGORY_RETORT, :name => 'インスタントラーメン')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'かに玉の素')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'カレールー')
Food.create(:category => FD_CATEGORY_RETORT, :name => '餃子')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'コーンスープ')
Food.create(:category => FD_CATEGORY_RETORT, :name => '吸い物の素')
Food.create(:category => FD_CATEGORY_RETORT, :name => '雑炊の素')
Food.create(:category => FD_CATEGORY_RETORT, :name => '茶漬けの素')
Food.create(:category => FD_CATEGORY_RETORT, :name => '中華丼')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ちらし寿司の素')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'チリソースの素')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'デミグラスソース')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ハヤシルー')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ホワイトソース')
Food.create(:category => FD_CATEGORY_RETORT, :name => '麻婆豆腐の素')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ミートソース')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'レトルトカレー')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'ワカメスープ')
Food.create(:category => FD_CATEGORY_RETORT, :name => 'その他のルー・レトルト')


# カテゴリ：調味料・たれ・ドリンク・スパイス
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ＸＯ醤')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'オイスターソース')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'オリーブオイル')
Food.create(:category => FD_CATEGORY_SPICE, :name => '黒こしょう')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'こしょう')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'コチュジャン')
Food.create(:category => FD_CATEGORY_SPICE, :name => '昆布茶')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ゴマ油')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'コンソメ')
Food.create(:category => FD_CATEGORY_SPICE, :name => '砂糖')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'サラダ油')
Food.create(:category => FD_CATEGORY_SPICE, :name => '塩')
Food.create(:category => FD_CATEGORY_SPICE, :name => '醤油')
Food.create(:category => FD_CATEGORY_SPICE, :name => '醤油（うすくち）')
Food.create(:category => FD_CATEGORY_SPICE, :name => '白だし')
Food.create(:category => FD_CATEGORY_SPICE, :name => '酢')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'すし酢')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ソース')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'テンメンジャン')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'トウバンジャン')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'トマトケチャップ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ドライイースト')
Food.create(:category => FD_CATEGORY_SPICE, :name => '鶏がらスープの素')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ナンプラー')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ねりゴマ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'はちみつ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'バニラエッセンス')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'バルサミコ酢')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ポン酢')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'マヨネーズ')
Food.create(:category => FD_CATEGORY_SPICE, :name => '味噌')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'みりん')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'メープルシロップ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'めんつゆ')
Food.create(:category => FD_CATEGORY_SPICE, :name => '柚子こしょう')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ラー油')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ワインビネガー')
Food.create(:category => FD_CATEGORY_SPICE, :name => '和風だし')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'その他の調味料')

Food.create(:category => FD_CATEGORY_SPICE, :name => 'ウーロン茶')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'オレンジジュース')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'コーラ')
Food.create(:category => FD_CATEGORY_SPICE, :name => '酒')
Food.create(:category => FD_CATEGORY_SPICE, :name => '紹興酒')
Food.create(:category => FD_CATEGORY_SPICE, :name => '焼酎')
Food.create(:category => FD_CATEGORY_SPICE, :name => '炭酸')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'トマトジュース')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ビール')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ブランデー')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ワイン（赤ワイン）')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ワイン（白ワイン）')
Food.create(:category => FD_CATEGORY_SPICE, :name => '水')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'その他の酒・ドリンク')

Food.create(:category => FD_CATEGORY_SPICE, :name => '焼肉のたれ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'しょうが焼きのたれ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'すき焼きのたれ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ごまだれ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ドレッシング（和）')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ドレッシング（洋）')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ドレッシング（中）')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'キムチの素')
Food.create(:category => FD_CATEGORY_SPICE, :name => '浅漬けの素')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'その他のたれ')

Food.create(:category => FD_CATEGORY_SPICE, :name => '青海苔')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'からし（チューブ）')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ゴマ')
Food.create(:category => FD_CATEGORY_SPICE, :name => '山椒')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'しょうが（チューブ）')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'タバスコ')
Food.create(:category => FD_CATEGORY_SPICE, :name => '唐辛子')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'にんにく（チューブ）')
Food.create(:category => FD_CATEGORY_SPICE, :name => '梅肉')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'バジル')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'パセリ')
Food.create(:category => FD_CATEGORY_SPICE, :name => '八角')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'マスタード')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'レモン汁')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ローズマリー')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'ローリエ')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'わさび（チューブ）')
Food.create(:category => FD_CATEGORY_SPICE, :name => 'その他の薬味・スパイス')


# カテゴリ：フルーツ
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'いちご')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'オレンジ')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'キウイ')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'なし')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'パイン')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'バナナ')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'ぶどう')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'みかん')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'メロン')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'りんご')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'レモン')
Food.create(:category => FD_CATEGORY_FURUIT, :name => 'その他のフルーツ')
