class FoodsController < ApplicationController
	def index
		@foods = Food.all
	end

	def new
		@foods = Food.all
		@categories = [FD_CATEGORY_MEAT, FD_CATEGORY_FISH, FD_CATEGORY_VEGE, FD_CATEGORY_EGG, FD_CATEGORY_RETORT, FD_CATEGORY_SPICE, FD_CATEGORY_FURUIT]
		@cat_name = [FD_NAME_MEAT, FD_NAME_FISH, FD_NAME_VEGE, FD_NAME_EGG, FD_NAME_RETORT, FD_NAME_SPICE, FD_NAME_FURUIT]
		@sub_categories = [FD_SUBCATEGORY_BEEF, FD_SUBCATEGORY_PORK, FD_SUBCATEGORY_CHICKEN, FD_SUBCATEGORY_FISH, FD_SUBCATEGORY_VEGE, FD_SUBCATEGORY_RICE, FD_SUBCATEGORY_NOODLE, FD_SUBCATEGORY_EGG, FD_SUBCATEGORY_POWDER, FD_SUBCATEGORY_PROCESS_MEAT, FD_SUBCATEGORY_PROCESS_VEGE, FD_SUBCATEGORY_PROCESS_FISH, FD_SUBCATEGORY_DRY, FD_SUBCATEGORY_PICKLE, FD_SUBCATEGORY_BOTTLE , FD_SUBCATEGORY_RETORT, FD_SUBCATEGORY_CONDIMENT, FD_SUBCATEGORY_DRINK, FD_SUBCATEGORY_SAUCE, FD_SUBCATEGORY_SPICE, FD_SUBCATEGORY_FRUIT]
		@sub_name = [FD_SUBNAME_BEEF, FD_SUBNAME_PORK, FD_SUBNAME_CHICKEN, FD_SUBNAME_FISH, FD_SUBNAME_VEGE, FD_SUBNAME_RICE, FD_SUBNAME_NOODLE, FD_SUBNAME_EGG, FD_SUBNAME_POWDER, FD_SUBNAME_PROCESS_MEAT, FD_SUBNAME_PROCESS_VEGE, FD_SUBNAME_PROCESS_FISH, FD_SUBNAME_DRY, FD_SUBNAME_PICKLE, FD_SUBNAME_BOTTLE , FD_SUBNAME_RETORT, FD_SUBNAME_CONDIMENT, FD_SUBNAME_DRINK, FD_SUBNAME_SAUCE, FD_SUBNAME_SPICE, FD_SUBNAME_FRUIT]
	end
end
